######################################################################
# Automatically generated by qmake (2.01a) Sze márc. 27 22:24:59 2019
######################################################################

TEMPLATE = app
TARGET =Mandel_zoom  
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += frakablak.h frakszal.h
SOURCES += frakablak.cpp frakszal.cpp main.cpp
QT += widgets
